### PR TITLE
Minimal effort to get this to build 

### PR DESCRIPTION
**Pull request by TomNaessens**
This doesn't build anymore due to issues of all kind. This MR is an effort to get it to build again on "modern" systems (e.g. my Macbook).

Minimal effort to get this to build. Things done:
- Add a docker-compose to run Mongoid
- Use [notroj/litmus.git](https://github.com/notroj/litmus) to get it to build again
- Make sure we can run specs again by bumping Rake, Unicorn and Nokogiri
- Fix the performance spec because my machine is too fast

To test:
1. Clone the repo
2. Run `bundle`
3. Run `./test/script.sh`
4. Verify all tests pass, the `perf_spec` might not, it's a funny tests that checks whether a performance benchmark is done within a second 😁 

There is one Litmus spec that fails:

```
 8. copy_shallow.......... 127.0.0.1 - - [12/Apr/2023:13:26:43 +0200] "MKCOL /litmus/ccsrc HTTP/1.1" 201 - 0.0006
127.0.0.1 - - [12/Apr/2023:13:26:43 +0200] "PUT /litmus/ccsrc/foo HTTP/1.1" 201 38 0.0007
127.0.0.1 - - [12/Apr/2023:13:26:43 +0200] "DELETE /litmus/ccdest HTTP/1.1" 404 - 0.0003
127.0.0.1 - - [12/Apr/2023:13:26:43 +0200] "COPY /litmus/ccsrc HTTP/1.1" 207 188 0.0008
127.0.0.1 - - [12/Apr/2023:13:26:43 +0200] "DELETE /litmus/ccsrc HTTP/1.1" 204 - 0.0005
127.0.0.1 - - [12/Apr/2023:13:26:43 +0200] "DELETE /litmus/ccdest/foo HTTP/1.1" 204 - 0.0004
 copy_shallow.......... FAIL (DELETE on `/litmus/ccdest/foo' should fail with 404: got 204)
 ```

Running the master branch on 0.13 (in a cursed Linux docker container), the spec passes:

```
 8. copy_shallow.......... 127.0.0.1 - - [12/Apr/2023:13:24:49 +0200] "MKCOL /litmus/ccsrc HTTP/1.1" 201 - 0.0003
127.0.0.1 - - [12/Apr/2023:13:24:49 +0200] "PUT /litmus/ccsrc/foo HTTP/1.1" 201 38 0.0004
127.0.0.1 - - [12/Apr/2023:13:24:49 +0200] "DELETE /litmus/ccdest HTTP/1.1" 404 - 0.0002
127.0.0.1 - - [12/Apr/2023:13:24:49 +0200] "COPY /litmus/ccsrc HTTP/1.1" 207 188 0.0005
127.0.0.1 - - [12/Apr/2023:13:24:49 +0200] "DELETE /litmus/ccsrc HTTP/1.1" 204 - 0.0002
127.0.0.1 - - [12/Apr/2023:13:24:49 +0200] "DELETE /litmus/foo HTTP/1.1" 404 - 0.0003
127.0.0.1 - - [12/Apr/2023:13:24:49 +0200] "DELETE /litmus/ccdest HTTP/1.1" 204 - 0.0003
 8. copy_shallow.......... pass
```

But there's a difference! The last `DELETE` action sent goes to `litmus/ccdest/foo` with Litmus 0.14 and to `litmus/ccdest` with Litmus 0.13. This is because of the following change: https://github.com/notroj/litmus/commit/6e2cd5ed698a812c419f5bcdbd22baf07b8c462e

When we "cherry-pick" that line into our cursed Linux docker container, rebuild Litmus, and run the spec on master on 0.13, we can see that the tests starts failing too:

```
 8. copy_shallow.......... 127.0.0.1 - - [12/Apr/2023:13:33:04 +0200] "MKCOL /litmus/ccsrc HTTP/1.1" 201 - 0.0002
127.0.0.1 - - [12/Apr/2023:13:33:04 +0200] "PUT /litmus/ccsrc/foo HTTP/1.1" 201 38 0.0004
127.0.0.1 - - [12/Apr/2023:13:33:04 +0200] "DELETE /litmus/ccdest HTTP/1.1" 404 - 0.0002
127.0.0.1 - - [12/Apr/2023:13:33:04 +0200] "COPY /litmus/ccsrc HTTP/1.1" 207 188 0.0005
127.0.0.1 - - [12/Apr/2023:13:33:04 +0200] "DELETE /litmus/ccsrc HTTP/1.1" 204 - 0.0003
127.0.0.1 - - [12/Apr/2023:13:33:04 +0200] "DELETE /litmus/ccdest/foo HTTP/1.1" 204 - 0.0002
 8. copy_shallow.......... FAIL (DELETE on `/litmus/ccdest/foo' should fail with 404: got 204)
```

So this is good news and bad news:
- Bad: dav4rack does not implement the Dav RFC completely
- Good: this branch is idempotent with master, meaning we don't have to fix this 😁

### CODE REVIEW

**Comment by pauc** [comment]
`bundle install` fails on linux with ruby 3.0.2. Full error message ->

```shell
Using dav4rack 0.3.0 from source at `.` and installing its executables
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/raindrops-0.8.0/ext/raindrops
/home/pau/.asdf/installs/ruby/3.0.2/bin/ruby -I /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0 -r ./siteconf20230412-629956-c62heg.rb extconf.rb
checking for mmap() in sys/mman.h... yes
checking for munmap() in sys/mman.h... yes
checking for mremap() in sys/mman.h... yes
checking for getpagesize() in unistd.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_io_blocking_region()... yes
checking for GCC 4+ atomic builtins... yes
creating Makefile

current directory: /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/raindrops-0.8.0/ext/raindrops
make DESTDIR\= clean

current directory: /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/raindrops-0.8.0/ext/raindrops
make DESTDIR\=
compiling linux_inet_diag.c
In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from /home/pau/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/ruby/defines.h:16,
                 from /home/pau/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/ruby/ruby.h:23,
                 from /home/pau/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/ruby.h:38,
                 from linux_inet_diag.c:1:
/usr/include/features.h:194:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  194 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
linux_inet_diag.c:17:12: fatal error: rubysig.h: No such file or directory
   17 | #  include <rubysig.h>
      |            ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:245: linux_inet_diag.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/raindrops-0.8.0 for inspection.
Results logged to /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/raindrops-0.8.0/gem_make.out

  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:91:in `run'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:43:in `block in make'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:35:in `each'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:35:in `make'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:64:in `block in build'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:157:in `build_extension'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:191:in `block in build_extensions'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `each'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `build_extensions'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/installer.rb:828:in `build_extensions'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/rubygems_gem_installer.rb:66:in `build_extensions'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/source/rubygems.rb:199:in `install'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/worker.rb:62:in `apply_func'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/worker.rb:54:in `loop'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/worker.rb:54:in `process_queue'
  /home/pau/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.28/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing raindrops (0.8.0), and Bundler cannot continue.

In Gemfile:
  unicorn was resolved to 4.2.0, which depends on
    raindrops
```

**Comment by TomNaessens** [comment]
Hmm, could you try again @pauc? I bumped unicorn (and raindrops) to the latest version, there were quite a bit behind 😁

**Comment by pauc** [comment]
> Hmm, could you try again @pauc? I bumped unicorn (and raindrops) to the latest version, there were quite a bit behind :grin: 

Tests pass now. The only one that fails is the Litmus one you mention on the description:
```
 8. copy_shallow.......... FAIL (DELETE on `/litmus/ccdest/foo' should fail with 404: got 204)
```

**Comment by TomNaessens** [comment]
Awesome, that's good, that's expected (and equivalent to master) 🥳

**Review by pauc — APPROVED** [review]

**Pull request merged**
